### ISSUE TITLE
esbuild-bundle.js saved with DOS-style newlines leads to issues in unix-like environments

### ISSUE THREAD

**Issue by mi-skam** [lgersman/ix-article-esbuild-2021#1]
Being in a wsl2 environment, I got:

```bash
u@win10-1:/mnt/c/Users/u/p/github/heise/lgersman/ix-article-esbuild-2021$ [dev]# ./bin/esbuild-bundle.mjs
/usr/bin/env: ‘node\r’: No such file or directory
```
It's easy to fix, with the help of `dos2unix` utility or like I did with the help of vim

```bash
u@win10-1:/mnt/c/Users/u/p/github/heise/lgersman/ix-article-esbuild-2021$ [dev]# vim bin/esbuild-bundle.mjs
:se ff=unix
:wq!
```

**Comment by lgersman** [comment]
Hi @mi-skam,

i just cloned the repository and grepped for `\r`

```
grep -Ilsr $'\r$' .
```

without any matches.

I would also be surprised the find `\r` in the sources because I use Linux for decades :-)

Even `vim` shows me no occurrence of `\r`in any of the source files (used `:set binary` and `:set list` to show me CR and LF characters) 

Might it be possible that you've accidentally edited the file in your windows environment ?

**Comment by lgersman** [comment]
Oha,

if you google around for `/usr/bin/env: 'node\r': No such file or directory` you'll find a lot of suggestions what might be the problem.

- Git converts line endings after `git clone` depending on your git settings  https://github.com/pyenv/pyenv/issues/1725#issuecomment-724689291

- npm tries to do the convert line endings (although only for bin files listed in `package.json`)

and so on. 

I am sure the problem is located somewhere in your toolchain (wsl/etc)

**Comment by mi-skam** [comment]
Ah, dang you're right. I probably checked it out with git running on PowerShell, which is probably the one causing this. Thx to your `grep` command I verifyied it, and found a lot of checked out files being converted by git - it seems. 😜🤣

Thx for your extensive reply!

P.S. Besides, when will be the release of part2 of the article series?

**Comment by lgersman** [comment]
It's actually ready but needs a bit of review :-)

I hope end of december.
